# Generated by Django 3.2.19 on 2023-06-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymaps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apt', models.IntegerField()),
                ('street_number', models.IntegerField()),
                ('street_name', models.CharField(max_length=255)),
                ('q1', models.CharField(max_length=255)),
                ('q2', models.CharField(max_length=255)),
                ('q3', models.CharField(max_length=255)),
                ('q4', models.CharField(max_length=255)),
                ('q5', models.CharField(max_length=255)),
            ],
        ),
    ]
