# Generated by Django 3.2.19 on 2023-06-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymaps', '0002_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='apt',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='street_number',
            field=models.CharField(max_length=255),
        ),
    ]
