# Generated by Django 3.2.19 on 2023-06-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymaps', '0003_auto_20230610_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='q1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='q2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='q3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='q4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='q5',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
