# Generated by Django 3.2.19 on 2023-06-25 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymaps', '0009_voters_finall'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voters_finall',
        ),
    ]
