# Generated by Django 3.2.19 on 2023-06-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymaps', '0011_voters_with_latlon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voters_with_latlon',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
