# Generated by Django 3.2.19 on 2023-06-25 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymaps', '0014_votelatlon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Votelatlon',
        ),
    ]
