# Generated by Django 3.2.19 on 2023-06-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymaps', '0016_votelatlon'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
