# Generated by Django 3.2.19 on 2023-06-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymaps', '0017_questionnaire_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='voter_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
