# Generated by Django 3.2.19 on 2023-07-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymaps', '0018_questionnaire_voter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='pct',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='ward',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
