# Generated by Django 3.2.19 on 2023-07-05 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymaps', '0019_auto_20230705_0939'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voter',
        ),
        migrations.DeleteModel(
            name='Voters_finallist',
        ),
        migrations.DeleteModel(
            name='Voters_with_latlon',
        ),
        migrations.DeleteModel(
            name='Voterslatlon',
        ),
    ]
