# Generated by Django 3.2.19 on 2023-07-07 05:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mymaps', '0022_alter_questionnaire_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 7, 5, 16, 15, 115970, tzinfo=utc)),
        ),
    ]
