# Generated by Django 3.2.19 on 2023-07-09 14:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mymaps', '0026_alter_questionnaire_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='q6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='created_at',
            field=models.CharField(default=datetime.datetime(2023, 7, 9, 14, 9, 1, 307405, tzinfo=utc), max_length=100),
        ),
    ]
