# Generated by Django 3.2.19 on 2023-07-12 19:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mymaps', '0027_auto_20230709_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='voters_list',
            name='visited',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='created_at',
            field=models.CharField(default=datetime.datetime(2023, 7, 12, 19, 15, 41, 387752, tzinfo=utc), max_length=100),
        ),
    ]
