# Generated by Django 3.2.19 on 2023-07-12 22:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mymaps', '0029_auto_20230713_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='created_at',
            field=models.CharField(default=datetime.datetime(2023, 7, 12, 22, 47, 52, 13925, tzinfo=utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='votelatlon',
            name='visited',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
