# Generated by Django 3.2.19 on 2023-07-12 22:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mymaps', '0030_auto_20230713_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votelatlon',
            name='visited',
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='created_at',
            field=models.CharField(default=datetime.datetime(2023, 7, 12, 22, 49, 10, 539791, tzinfo=utc), max_length=100),
        ),
    ]
